server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false


#server:
#  port: 8189
#  servlet:
#    context-path: /app
#spring:
#  datasourse:
#    driver-class-name: org.h2.Driver
##    driver-class-name: org.postgresql.Driver
##    url: jdbc:postgresql://localhost:5432/customers
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
##    database:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
##        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2


